# Generated by Django 4.1.3 on 2022-12-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobworker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=32)),
                ('WorkerName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveBigIntegerField()),
                ('COlour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.colour')),
                ('FromName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_name', to='management.jobworker')),
                ('Quality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.quality')),
                ('ToName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_name', to='management.jobworker')),
            ],
        ),
        migrations.AlterField(
            model_name='dyeingstock',
            name='Dyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.jobworker'),
        ),
        migrations.AlterField(
            model_name='factorystock',
            name='Factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.jobworker'),
        ),
        migrations.AlterField(
            model_name='finishingstock',
            name='Finisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.jobworker'),
        ),
        migrations.AlterField(
            model_name='officestock',
            name='Office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.jobworker'),
        ),
        migrations.DeleteModel(
            name='Dyer',
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
        migrations.DeleteModel(
            name='Finisher',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
