# Generated by Django 4.1.3 on 2022-12-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorystock',
            name='Factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.factory'),
        ),
        migrations.AlterField(
            model_name='officestock',
            name='Office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.office'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderNo',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='orderlist',
            unique_together={('Customer', 'Order')},
        ),
    ]
