# Generated by Django 4.1.3 on 2022-12-11 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Colour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.colour')),
                ('Quality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.quality')),
            ],
        ),
        migrations.CreateModel(
            name='FinishingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Colour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.colour')),
                ('Finisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.finisher')),
                ('Quality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.quality')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Colour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.colour')),
                ('Quality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.quality')),
            ],
        ),
        migrations.CreateModel(
            name='DyeingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Colour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.colour')),
                ('Dyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.dyer')),
                ('Quality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.quality')),
            ],
        ),
    ]
