# Generated by Django 4.2.4 on 2025-03-12 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='Date',
            field=models.DateField(default=datetime.date(2025, 3, 12)),
            preserve_default=False,
        ),
    ]
