# Generated by Django 4.2.4 on 2025-03-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_movement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='Colour',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='SerialNo',
        ),
        migrations.AlterUniqueTogether(
            name='serialno',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='serialno',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='serialno',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='serialno',
            name='Quality',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
        migrations.DeleteModel(
            name='SerialNo',
        ),
    ]
