# Generated by Django 4.2.4 on 2025-03-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_orderlist_colour_remove_orderlist_serialno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyeingstock',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factorystock',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finishingstock',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movement',
            name='Quantity',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='officestock',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='otherconsumption',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
