# Generated by Django 4.2.4 on 2025-03-14 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_dyeingstock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherconsumption',
            name='Date',
            field=models.DateField(default=datetime.date(2025, 3, 14)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherconsumption',
            name='Remark',
            field=models.TextField(null=True),
        ),
    ]
